### PR TITLE
Introduced Vanilla Kubernetes

### PR DESCRIPTION
**Pull request by rlenferink**
Kubernetes is introduced in this commit. A lot of resources from the minikube example could be re-used. This has been tested using OpenShift and Tectonic as container orchestrators. Both are working fine.

CLA is already submitted to https://cla.developers.google.com/

### CODE REVIEW

**Comment by tpryan** [comment]
First off, thanks so much for contributing this.  I would like to integrate it. But I am a little wary about a couple of the labels and names. Whether your running on Container Engine (which we just renamed Kubernetes Engine) or Minikube, you are running on Kubernetes. 

So I think labeling the new build targets and files "kubernetes" is kinda confusing. It's all Kubernetes.  It's "Vanilla Kubernetes"  or "Self Managed Kubernetes" (since GKE and minikube manage it for you) or something else.  I gently push back to you to come up with something you like.  But other than that, I'm very happy to have your contribution. 

Also I should rename the Container Engine portion to be "GKE" or something like that, but that's on me to do.

**Comment by rlenferink** [comment]
I started with adjusting the 'Getting Started with ....' headings a little bit by mentioning the usage of GCE, Vanilla Kubernetes or Minikube. I agree we have to clarify which Kubernetes can be used. But I'm also thinking the make deploy.kubernetes / clean.kubernetes are clearly described in the readme file. However, when an additional Kubernetes configuration will be added, I think it's indeed good to clarify it a little bit more.

Is the current clarification good enough for you? I will continue just a long I need for the code to be implemented ;)

**Comment by rlenferink** [comment]
@tpryan are you still considering to integrate this ?

**Comment by tpryan** [comment]
Yep sorry about that.

**Comment by tpryan** [comment]
I spoke too soon.

**Pull request merged**
